---
title: "Final_Project_Writeup"
author: "Kaden Pickering"
date: "5/10/2022"
output: html_document


The shiny app that I created for this final project uses National Hockey League data ranging all the way back to 2008 for every team in existence since that time. The statistics that came with my data set were fairly self-explanatory with the exception of a few, so I decided to leave the variables that were hard to understand out of my project. The purpose of my Shiny App is to answer some questions based on the data given in the data set. I play hockey myself so I had hunches about what kind of trends there could be within the data. I first posed the question of “do more successful shot attempts that make it to the net lead to more goals on the powerplay?” To start, considering my data set has about 180,000 observations, I decided to shrink my data set to only look at the Pittsburgh Penguins in 2017. From there, I begged the question of “Does more Powerplay ice time lead to more goals throughout a season?” using the entire data set with all teams available to choose from. There were a few interesting results, but for the most part my hypothesis was correct. Lastly, I left my third panel up to the discretion of the user. They may choose whatever team, statistic for the x-axis, and statistic for the y-axis they desire and see trends and correlations on a reactive scatterplot. Overall, my shiny app was straight forward and simple but answered the questions that I had and most question you may have about the data set. 

My project followed the guidelines of what a “good data visualization” is for the most part. The one part of the project that may seem “unethical” or considered to be hiding some of the truth about the statistics would be my first panel. I chose to use the Pittsburgh Penguins in 2017 because that is the year they won the Stanley Cup. Since that is the case, they were obviously the best team in the NHL that year. To show visualizations of the best team in the NHL and their success rate of scoring when shots go through to the net may have been biased in one direction to show a trend. While unaware of my bias and ethical implications to begin with, in hindsight, maybe it would have been better to use a different year for the Pittsburgh team or even a different team in general. As far as ethics and good visualizations go for the rest of my project, I think my second and third panels do a great job of telling the whole truth as it shows in the data. The user has the option to look at any team from any season in my second panel for powerplay ice time in a season compared to their goals scored. In my third panel, the user also has the option to look at any team over many years to see trends in whatever statistic they decide. I did leave some statistics from the data set out because they don’t make sense to someone who hasn’t studied the data set, but I don’t believe that harmed the integrity of the project at all whatsoever. 

With respect to our Introduction to Data Visualization section, I think I utilized the concepts described within well. My color scales used throughout each slide are variable depending on what the user chooses to set the scheme as. I decided to include the theme customizer in my project so that each user can set the theme to whatever suits their preferences best. I think that was a huge asset because not everyone sees color schemes and themes the same way. Therefore, with the ability to set the theme to whatever they want, everyone can enjoy the visualizations in their own way. My scatterplots and bar charts are all proportional and have word sizing that are easily readable. I don’t think there is any deception within my images and tell the story of the data honestly and to the best of their ability. 

Expressing uncertainty within my shiny app was not needed because of the volume of data points I was working with. Bar charts can be bad for describing a data set because they leave some points and outliers to be minimized by the majority. In my case, the bar charts used are for total goals throughout a season for each team. There are no instances where outliers would affect the outcome. Also, wherever there may have been uncertainty and outliers, I used graphs to straighten such instances out. For instance, I made my own category of proportion of shots that get through to the net so that my data wouldn’t be skewed one way because of the column “shot attempts”. Not all shot attempts end up on goal and for that reason, I had to remove the column from my data set to be relative to how many shots got through to the net compared to the amount of ice time a team had on the powerplay. I don’t think any whisker or lollipop charts were needed for my data because of the straight-forward nature of the data set. 

The work that I did with this data set was only scratching the surface of what would be possible. In the future if I were to continue researching this data set, I would want to describe the rest of the columns within the data set to include them in a way that a user would understand them. Many of the ratios and outputs in the original data set were specific to someone who had made it. To really get down to the bottom of what all the columns meant, it would take more research and more calculations. Some limitations that would have been nice to get around within the data set were player statistics. There were no individual player statistics within this set, and it would be interesting to do some analysis on a team’s success compared to a players success. I would ask questions such as were the most successful players throughout a season on the best teams? Or would there be no correlation between team success and player success? If time allowed and the data set were more extensive, some visualizations and analysis between player and team correlations would be very interesting to do. By working with what I had and making the most of my data set, I think my shiny app turned out great and answered the questions that I wanted to pose. 

