---
title: "Final_Project"
author: "Kaden Pickering"
date: "3/21/2022"
output: html_document
---

```{r}
library(tidyverse) 

hockey_data <- read_csv("all_teams.csv") 
pittsburgh_penguins <- hockey_data %>%
  filter(team == "PIT") 
```

```{r}
all_situations <- hockey_data %>%
  filter(situation == "all") 

even_strength <- hockey_data %>%
  filter(situation == "5on5")

power_play <- hockey_data %>%
  filter(situation == "5on4")

short_handed <- hockey_data %>%
  filter(situation == "4on5")


other_situations <- hockey_data %>%
  filter(situation == "other") 
```

# Get the data set into a workable place that I can wrap my head around
```{r}
PP_all_situations <- pittsburgh_penguins %>%
  filter(situation == "all") 

PP_even_strength <- pittsburgh_penguins %>%
  filter(situation == "5on5")

PP_power_play <- pittsburgh_penguins %>%
  filter(situation == "5on4")

PP_short_handed <- pittsburgh_penguins %>%
  filter(situation == "4on5")

PP_other_situations <- pittsburgh_penguins %>%
  filter(situation == "other") 
```

# Start even smaller to get some perspective
```{r}
Pitt_2017 <- pittsburgh_penguins %>%
  filter(season == "2017") %>%
  mutate(propShotsThrough = shotsOnGoalFor / shotAttemptsFor) 
   #rename(goalsFor = goalsFor)
```


```{r}
PP_all_situations_small <- Pitt_2017 %>%
  filter(situation == "all") 

PP_even_strength_small <- Pitt_2017 %>%
  filter(situation == "5on5")

PP_power_play_small <- Pitt_2017 %>%
  filter(situation == "5on4")

PP_short_handed_small <- Pitt_2017 %>%
  filter(situation == "4on5")

PP_other_situations_small <- Pitt_2017 %>%
  filter(situation == "other")
```
 
# The more shots, the better chance of scoring...right? Let's see if that theory checks out in all situations. 

```{r}
shotsThrough_sub <- Pitt_2017 %>% 
  filter(opposingTeam == "WSH")

PP_short_handed <- pittsburgh_penguins %>%
  filter(situation == "4on5")
```

```{r}
PPtableData <- Pitt_2017 %>%
  select(gameId, situation, shotsOnGoalFor, missedShotsFor, blockedShotAttemptsFor, shotAttemptsFor, goalsFor, propShotsThrough) %>%
  arrange(desc(propShotsThrough)) 
```

```{r}
# Look at correlation between PP icetime and total goals scored on the season for each team 

season_2017 <- hockey_data %>%
  filter(situation == "5on4") %>%
  select(team, season, goalsFor, iceTime) 
  

```

```{r}
library(tidyverse) 

powerplay_2017_all <- season_2017 %>%
  group_by(team, season) %>%
  mutate(sumgoals = cumsum(goalsFor)) %>%
  mutate(sumice = cumsum(iceTime)/60) %>%
  filter(sumice == max(sumice)) %>%
  mutate(prop_goalsperice = sumgoals/sumice) %>%
  mutate(team = str_replace(string = team, "N.J", "NJD")) %>%
  mutate(team = str_replace(team, "S.J", "SJS")) %>%
  mutate(team = str_replace(team, "T.B", "TBL")) %>%
  mutate(team = str_replace(team, "L.A", "LAK")) %>%
  distinct(team, .keep_all = TRUE) 
  
    
```

```{r}
library(tidyverse) 

icetime_table_data <- powerplay_2017_all %>%
  select(team, season, sumgoals, sumice, prop_goalsperice) %>%
  mutate(team = str_replace(string = team, "N.J", "NJD")) %>%
  mutate(team = str_replace(team, "S.J", "SJS")) %>%
  mutate(team = str_replace(team, "T.B", "TBL")) %>%
  mutate(team = str_replace(team, "L.A", "LAK")) %>% 
  distinct() 
```



```{r}

var_choices <- names(hockey_data)[c(25:30,39:41, 56, 73:78, 86, 89)]

library(shiny)
library(tidyverse) 
library(bslib)
library(plotly)
thematic::thematic_shiny(font = "auto")

ui <- fluidPage(
  theme = bs_theme(),
  
  tabsetPanel(
    tabPanel("More Shots = More Goals?", fluid = TRUE, 
  titlePanel("Do More Successful Shot Attempts Lead to More Goals? (Pittsburgh Penguins in 2017)"), 
  
  sidebarLayout(sidebarPanel(
    selectInput("opponentchoice",
    label = "Choose an Opponent", choices = levels(factor(Pitt_2017$opposingTeam)),
    selected = "STL")),
                mainPanel(plotlyOutput("scatterplot"),
                          tableOutput("goaltable")))
                )
  
,
  tabPanel("IceTime", fluid = TRUE, 
           titlePanel("More Powerplay Icetime = More Goals?"), 
           
           sidebarLayout(sidebarPanel(
             selectInput("teamchoice", 
            label = "Choose a Team", choices= levels(factor(icetime_table_data$team)), selected = "NYR")), 
            mainPanel(plotOutput("barchart"),
                         tableOutput("icetimeTable"))
           )
), 
  tabPanel("YourChoice", fluid = TRUE, 
           titlePanel("What Are You Curious About?"), 
           
           sidebarLayout(sidebarPanel(
             selectizeInput("clubchoice", 
            label = "Choose a Hockey Team", choices= levels(factor(hockey_data$team)), 
            selected = "PIT")),
            selectInput("varchoice1", label = "Choose a Statistic for the X-Axis", 
                         choices = var_choices)),
           selectInput("varchoice2", label = "Choose a Statisitc for the Y-Axis", 
                         choices = var_choices),
            mainPanel(plotlyOutput("yourchoicegraph")) 

)
)) 

server <- function(input, output, session) {
  
  bs_themer()
  
  shotsThrough_sub <- reactive({
    Pitt_2017 %>% filter(opposingTeam == input$opponentchoice)
  })
  
  iceTime_sub <- reactive({
   icetime_table_data %>% filter(team == input$teamchoice)
  })
  
  yourChoiceSub <- reactive({
   hockey_data %>% filter(team == input$clubchoice) 
  })
  
  scatter_plot <- reactive({ 
    ggplot(shotsThrough_sub(), aes(x = goalsFor, y = propShotsThrough)) +
  geom_point() + 
      geom_smooth(method = lm) +
    theme_classic() + 
      theme(axis.text = element_text(size = 15)) + 
      theme(text = element_text(size = 15)) +
    facet_wrap(~ situation) +
      labs(x = "Goals Scored", y = "Proportion of Shot Attempts On Net")
  })
  
  bar_chart <- reactive({
    ggplot(iceTime_sub(), aes(x = reorder(season, -sumgoals), y = sumgoals, fill = season)) +
      geom_col() +
      theme_classic() +
      theme(axis.text = element_text(size = 15)) + 
      theme(axis.text.x = element_text(angle = 90, size = 15)) +
      theme(text = element_text(size = 15)) +
      scale_color_viridis_c() +
      labs(x = "Season", y = "PP Goals Scored" ) +
      theme(legend.position = "none") 
  })
  
  choice_viz <- reactive ({
    ggplot(yourChoiceSub(), aes(x = .data[[input$varchoice1]], y = .data[[input$varchoice2]])) +
             geom_point() +
            geom_smooth(method = lm) +
            theme_classic() +
      theme(axis.text = element_text(size = 15)) + 
      theme(text = element_text(size = 15)) 
  })
  
  output$scatterplot <- renderPlotly({
    ggplotly(scatter_plot()) 
  })
  
  output$goaltable <- renderTable({
    goalFilter <- subset(PPtableData, Pitt_2017$opposingTeam == input$opponentchoice) %>%
      arrange(desc(propShotsThrough))
      
  })
  
  output$icetimeTable <- renderTable({
    PPFilter <- subset(icetime_table_data, powerplay_2017_all$team == input$teamchoice) %>%
      arrange(desc(sumice))
      
  })  
  
  output$barchart <- renderPlot({
    bar_chart()
  })
  
  output$yourchoicegraph <- renderPlotly({
    ggplotly(choice_viz())
  })
}

shinyApp(ui, server)
```



                 
                 